# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15N31P9yPIi_RoOvy1KTTxOq7KBsMOf52
"""

!pip install streamlit
!pip install plotly
import streamlit as st
import pandas as pd
import plotly.express as px
diagnostica = pd.read_csv("df_diagnostico.csv")
somativa = pd.read_csv("df_somativa.csv")
diag_habilidades_abaixo = diagnostica[diagnostica["HABILIDADE - FAIXA"].isin(["Baixo", "Médio Baixo"])]
diag_habilidades_abaixo = diag_habilidades_abaixo.sort_values("HABILIDADE - ACERTO %")
fig = px.bar(
    diag_habilidades_abaixo,
    x="HABILIDADE - DESCRIÇÃO",
    y="HABILIDADE - ACERTO %",
    color="HABILIDADE - FAIXA",
    orientation="h",
    title="Habilidades que precisam ser melhoradas",
    text="HABILIDADE - ACERTO %"
)

fig.update_traces(texttemplate='%{text:.1f}%', textposition='outside')
fig.update_layout(xaxis_title="Habilidade", yaxis_title="Percentual de Acerto")
st.plotly_chart(fig, use_container_width=True)
